version: '3'
services:

  bot:
    container_name: top_decollage_bot
    image: ghcr.io/manusancho/top_decollage:0.0.1
    ports:
      - "8666:8666"
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - redis
      - default
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: top_decollage_redis
    restart: always
    networks:
      - redis

networks:
  redis:
  default:
